In [ ]:
### Plotting precipitation 

In [2]:
import xarray as xr

ds = xr.open_dataset("/storage/homefs/ge24z347/LISFLOOD_FP_8_1/build/Zell_2m/Zell_2m_1.nc")
ds

<xarray.Dataset> Size: 768B
Dimensions:         (time: 11, x: 5, y: 3)
Coordinates:
  * time            (time) float32 44B 0.0 1.0 2.0 3.0 4.0 ... 7.0 8.0 9.0 10.0
  * x               (x) float64 40B 2.702e+06 2.704e+06 ... 2.706e+06 2.706e+06
  * y               (y) float64 24B 1.256e+06 1.256e+06 1.258e+06
Data variables:
    rainfall_depth  (time, y, x) float32 660B ...
Attributes:
    description:  Cropped ICON rainfall, realization 1
    history:      Created on 2025-12-16
    source:       ICON forecast cropped to DEM box (no resampling)

In [10]:
import xarray as xr

path = "/storage/homefs/ge24z347/Liestal_event/Data_forprocess/COSMO/cosmo1e_2022-05-05T12.nc"

ds = xr.open_dataset(path, decode_cf=False)
ds

<xarray.Dataset> Size: 680MB
Dimensions:                  (forecast_reference_time: 1, lead_time: 34,
                              realization: 11, y: 640, x: 710)
Coordinates:
  * lead_time                (lead_time) float64 272B 0.0 3.6e+03 ... 1.188e+05
  * forecast_reference_time  (forecast_reference_time) float64 8B 1.652e+09
  * realization              (realization) int32 44B 0 1 2 3 4 5 6 7 8 9 10
  * y                        (y) int64 5kB 840500 841500 ... 1478500 1479500
  * x                        (x) int64 6kB 2255500 2256500 ... 2963500 2964500
Data variables:
    precipitation_amount     (forecast_reference_time, lead_time, realization, y, x) float32 680MB ...
    time                     (forecast_reference_time, lead_time) int64 272B ...
Attributes:
    source:        COSMO-1E
    crs:           EPSG:2056
    grid_mapping:  {"epsg_code": "EPSG:2056",\n                         "long...

In [11]:
ds.forecast_reference_time

<xarray.DataArray 'forecast_reference_time' (forecast_reference_time: 1)> Size: 8B
array([1.651752e+09])
Coordinates:
  * forecast_reference_time  (forecast_reference_time) float64 8B 1.652e+09
Attributes:
    _FillValue:  nan
    units:       seconds since 1970-01-01
    calendar:    proleptic_gregorian

In [6]:
COSMO_flowdepth = xr.open_dataset("/storage/homefs/ge24z347/LISFLOOD_FP_8_1/build/Zell_2m/Zell_2m_COSMO_2022-05-05T12-00.nc")
COSMO_flowdepth 

<xarray.Dataset> Size: 13GB
Dimensions:                  (forecast_reference_time: 1, lead_time: 11,
                              realization: 11, x: 2500, y: 1500)
Coordinates:
  * forecast_reference_time  (forecast_reference_time) datetime64[ns] 8B 2022...
  * lead_time                (lead_time) float64 88B 0.0 3.6e+03 ... 3.6e+04
  * realization              (realization) int32 44B 0 1 2 3 4 5 6 7 8 9 10
  * x                        (x) float64 20kB 2.702e+06 2.702e+06 ... 2.707e+06
  * y                        (y) float64 12kB 1.258e+06 1.258e+06 ... 1.255e+06
Data variables:
    time                     (forecast_reference_time, lead_time) datetime64[ns] 88B ...
    water_depth              (forecast_reference_time, lead_time, realization, y, x) float32 2GB ...
    vel_x_c                  (forecast_reference_time, lead_time, realization, y, x) float32 2GB ...
    vel_y_c                  (forecast_reference_time, lead_time, realization, y, x) float32 2GB ...
    flux_x_c                 (forecast_reference_time, lead_time, realization, y, x) float32 2GB ...
    flux_y_c                 (forecast_reference_time, lead_time, realization, y, x) float32 2GB ...
    vel_mag                  (forecast_reference_time, lead_time, realization, y, x) float32 2GB ...
    flux_mag                 (forecast_reference_time, lead_time, realization, y, x) float32 2GB ...
Attributes:
    Conventions:  CF-1.8
    source:       LISFLOOD ASCII ensemble stacked to COSMO-like forecast form...
    crs:          EPSG:2056

In [9]:
wd_r2 = COSMO_flowdepth["water_depth"].sel(realization=2)
wd_r2.values

array([[[[0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
          0.000e+00],
         [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
          0.000e+00],
         [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
          0.000e+00],
         ...,
         [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
          0.000e+00],
         [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
          0.000e+00],
         [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
          0.000e+00]],

        [[0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
          0.000e+00],
         [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
          0.000e+00],
         [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
          0.000e+00],
         ...,
         [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
          0.000e+00],
         [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.

In [5]:

ds_flowdepth = xr.open_dataset("/storage/homefs/ge24z347/LISFLOOD_FP_8_1/build/Zell_2m/Zell_2m_Combiprecip.nc")
ds_flowdepth  

<xarray.Dataset> Size: 1GB
Dimensions:         (REFERENCE_TS: 11, y: 1500, x: 2500)
Coordinates:
  * REFERENCE_TS    (REFERENCE_TS) datetime64[ns] 88B 2022-05-05T12:00:00 ......
  * y               (y) float64 12kB 1.258e+06 1.258e+06 ... 1.255e+06 1.255e+06
  * x               (x) float64 20kB 2.702e+06 2.702e+06 ... 2.707e+06 2.707e+06
    spatial_ref     int64 8B ...
Data variables:
    water_depth     (REFERENCE_TS, y, x) float32 165MB ...
    vel_x_c         (x, REFERENCE_TS, y) float32 165MB ...
    vel_y_c         (y, REFERENCE_TS, x) float32 165MB ...
    flux_x_c        (x, REFERENCE_TS, y) float32 165MB ...
    flux_y_c        (y, REFERENCE_TS, x) float32 165MB ...
    vel_mag         (x, REFERENCE_TS, y) float32 165MB ...
    flux_mag        (x, REFERENCE_TS, y) float32 165MB ...
    discharge_cell  (y, x, REFERENCE_TS) float32 165MB ...
    speed_cell      (y, x, REFERENCE_TS) float32 165MB ...
Attributes:
    Conventions:    CF-1.8
    source:         LISFLOOD single-member ASCII series, cell-centred on wate...
    deterministic:  true

In [34]:
rain_6 = ds.rainfall_depth.isel(time=8)
rain_6.values

array([[4.1388073 , 4.1388073 , 4.1388073 , 4.1388073 , 4.1388073 ],
       [4.1388073 , 4.1388073 , 4.1388073 , 4.1388073 , 4.1388073 ],
       [3.54983807, 3.83302712, 3.83302712, 3.83302712, 4.1388073 ]])

In [1]:
import xarray as xr
import numpy as np
import rasterio
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from matplotlib.colors import BoundaryNorm, ListedColormap
from pathlib import Path

# --------------------------------------------------
# Paths
# --------------------------------------------------
nc_file  = "/storage/homefs/ge24z347/Liestal_event/Data_forprocess/Combiprecip/CPC_00060_H_20220502000000_20220508230000.nc"
dem_file = "/storage/homefs/ge24z347/LISFLOOD_FP_8_1/build/Zell_2m/Zell_2m.dem"

out_dir  = Path("/storage/homefs/ge24z347/Liestal_event/ZELL_PLOTS/Combiprecip_Zell_2m_precipitation")
out_dir.mkdir(parents=True, exist_ok=True)

# --------------------------------------------------
# Load data
# --------------------------------------------------
ds = xr.open_dataset(nc_file, decode_times=True)
cpc = ds["CPC"]
time_coord = "REFERENCE_TS"

# --------------------------------------------------
# DEM bounds
# --------------------------------------------------
with rasterio.open(dem_file) as src:
    left, bottom, right, top = src.bounds

y_vals = cpc["y"]
x_vals = cpc["x"]

y_slice = slice(bottom, top) if y_vals[0] < y_vals[-1] else slice(top, bottom)
x_slice = slice(left, right) if x_vals[0] < x_vals[-1] else slice(right, left)

# --------------------------------------------------
# Times
# --------------------------------------------------
times = [
    "2022-05-05T12:00:00",
    "2022-05-05T13:00:00",
    "2022-05-05T14:00:00",
    "2022-05-05T15:00:00",
    "2022-05-05T16:00:00",
    "2022-05-05T17:00:00",
    "2022-05-05T18:00:00",
    "2022-05-05T19:00:00",
    "2022-05-05T20:00:00",
    "2022-05-05T21:00:00",
    "2022-05-05T22:00:00",
]

# --------------------------------------------------
# AUTO-DETECT MAXIMUM VALUE
# --------------------------------------------------
cpc_max = float(cpc.max())
vmax = int(np.ceil(cpc_max / 5) * 5)
print("Detected CPC max:", cpc_max, "---> Rounded to:", vmax)

# --------------------------------------------------
# BINS STARTING FROM 1
# --------------------------------------------------
# 1–5, 5–10, 10–15, ...
bounds = np.concatenate(([1], np.arange(5, vmax + 5, 5)))
n_bins = len(bounds)

# --------------------------------------------------
# COLORMAP
# --------------------------------------------------
mswiss_15 = [
    "#F9844A", "#FBB476", "#FDD8A3",
    "#FFFFCC", "#F0E68C",
    "#C7E9B4", "#7FCDBB",
    "#41B6C4", "#1D91C0",
    "#225EA8", "#253494",
    "#081D58", "#31183b",
    "#70265c", "#bc3754"
]

base_cmap = ListedColormap(mswiss_15)
continuous = plt.cm.get_cmap(base_cmap)
colors = continuous(np.linspace(0, 1, n_bins))
cmap = ListedColormap(colors)
norm = BoundaryNorm(bounds, cmap.N)

# --------------------------------------------------
# LOOP
# --------------------------------------------------
for t in times:
    cpc_t = cpc.sel({time_coord: t})
    cpc_win = cpc_t.sel(x=x_slice, y=y_slice)

    # Zero rainfall becomes transparent
    cpc_masked = cpc_win.where(cpc_win != 0)

    fig, ax = plt.subplots(figsize=(8, 6))

    im = cpc_masked.plot.pcolormesh(
        ax=ax,
        cmap=cmap,
        norm=norm,
        edgecolors="k",
        linewidth=0.4,
        cbar_kwargs={
            "label": "precipitation amount (mm)",
            "ticks": bounds,   # Now: 1,5,10,15,...
        }
    )

    rect = Rectangle((left, bottom), right - left, top - bottom,
                     fill=False, edgecolor="red", linewidth=1.2)
    ax.add_patch(rect)

    ax.set_aspect("equal")
    ax.set_title(f"Precipitation at {t}")
    ax.set_xlabel("")
    ax.set_ylabel("")

    outfile = out_dir / f"CPC_{t.replace(':','')}.png"
    plt.tight_layout()
    plt.savefig(outfile, dpi=200)
    plt.close()

    print("Saved:", outfile)

print("Done.")


Detected CPC max: 60.749366760253906 ---> Rounded to: 65


/tmp/ipykernel_1415598/2112439429.py:82: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  continuous = plt.cm.get_cmap(base_cmap)


Saved: /storage/homefs/ge24z347/Liestal_event/ZELL_PLOTS/Combiprecip_Zell_2m_precipitation/CPC_2022-05-05T120000.png
Saved: /storage/homefs/ge24z347/Liestal_event/ZELL_PLOTS/Combiprecip_Zell_2m_precipitation/CPC_2022-05-05T130000.png
Saved: /storage/homefs/ge24z347/Liestal_event/ZELL_PLOTS/Combiprecip_Zell_2m_precipitation/CPC_2022-05-05T140000.png
Saved: /storage/homefs/ge24z347/Liestal_event/ZELL_PLOTS/Combiprecip_Zell_2m_precipitation/CPC_2022-05-05T150000.png
Saved: /storage/homefs/ge24z347/Liestal_event/ZELL_PLOTS/Combiprecip_Zell_2m_precipitation/CPC_2022-05-05T160000.png
Saved: /storage/homefs/ge24z347/Liestal_event/ZELL_PLOTS/Combiprecip_Zell_2m_precipitation/CPC_2022-05-05T170000.png
Saved: /storage/homefs/ge24z347/Liestal_event/ZELL_PLOTS/Combiprecip_Zell_2m_precipitation/CPC_2022-05-05T180000.png
Saved: /storage/homefs/ge24z347/Liestal_event/ZELL_PLOTS/Combiprecip_Zell_2m_precipitation/CPC_2022-05-05T190000.png
Saved: /storage/homefs/ge24z347/Liestal_event/ZELL_PLOTS/Combipr